services:
  app:
    image: 3a119f63d294
    build: .
    ports:
      - "7001:7001"
    depends_on:
      - mysql
      - redis
    env_file:
      - ./.env
    volumes:
      - ./logs:/app/logs
    restart: always

  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    env_file:
      - ./.env
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./deploy/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./deploy/mysql/initdb.d:/docker-entrypoint-initdb.d
    restart: always
    command: --authentication-policy=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  redis:
    image: 9203d186d252
    ports:
      - "6379:6379"
    env_file:
      - ./.env
    volumes:
      - ./redis-data:/data
    restart: always

  nginx:
    image: nginx:1.21-alpine
    ports:
      - "80:80"
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app/public:/var/www/api.example.com/public
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - app
    restart: always 